### ISSUE TITLE
build: Automatically Build Binaries

### ISSUE THREAD

**Issue by elithrar** [ejcx/cf#1]
We should automatically build binaries for the major platforms: Windows, Darwin (macOS) & Linux via TravisCI.

Refer to https://github.com/cloudflare/logshare/blob/master/.travis.yml 

(I'll take a look this weekend)

**Comment by grempe** [comment]
👍

The current release binaries don't include the worker capabilities, and I've been unable to get the tool to compile against current `cloudflare-go` code.

```
❯ make dist-osx
GOOS=darwin go build -o dist/cf-osx
# github.com/ejcx/cf/cmd
cmd/api.go:1142:17: api.CreateWorkerRoute undefined (type *cloudflare.API has no field or method CreateWorkerRoute)
cmd/api.go:1142:44: undefined: cloudflare.WorkerRoute
cmd/api.go:1150:17: api.UpdateWorkerRoute undefined (type *cloudflare.API has no field or method UpdateWorkerRoute)
cmd/api.go:1150:53: undefined: cloudflare.WorkerRoute
cmd/api.go:1158:17: api.ListWorkerRoutes undefined (type *cloudflare.API has no field or method ListWorkerRoutes)
cmd/api.go:1180:17: api.UploadWorker undefined (type *cloudflare.API has no field or method UploadWorker)
cmd/api.go:1180:32: undefined: cloudflare.WorkerRequestParams
cmd/api.go:1187:17: api.DeleteWorker undefined (type *cloudflare.API has no field or method DeleteWorker)
cmd/api.go:1187:32: undefined: cloudflare.WorkerRequestParams
cmd/api.go:1194:17: api.ListWorkerScripts undefined (type *cloudflare.API has no field or method ListWorkerScripts)
cmd/api.go:1194:17: too many errors
make: *** [dist-osx] Error 2
```

**Comment by elithrar** [comment]
This repo pins to an older version of cloudflare-go - v0.8.5 - and you’ll
want something later than
https://github.com/cloudflare/cloudflare-go/commit/bc8641ae4dcf6f74c13afdb486129004f5aea7a9
to grab the Workers API.

**Comment by elithrar** [comment]
@ejcx - get Patryk to cut a new release (I did the last one before I left) and then update deps?
